networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${NETWORK_PREFIX}.0/20"
          gateway: "${NETWORK_PREFIX}.1"
  web:
    external: true

secrets:
  smtpd-password:
    file: ../.secrets/smtpd_password.secret
  smtpd-user:
    file: ../.secrets/smtpd_user.secret

services:
  bareos-api:
    # Traefik labels are suggested as an example for people using Traefik,
    # remove them if you are using another reverse proxy.
    labels:
      traefik.enable: true
      traefik.http.routers.bareos-api.entrypoints: websecure
      traefik.http.routers.bareos-api.rule: "Host(`api.${HOSTNAME}`)"
      traefik.http.routers.bareos-api.tls.certresolver: myresolver   
      traefik.http.services.bareos-api.loadbalancer.server.port: 8000
    networks:
      web:
      default:
        ipv4_address: "${NETWORK_PREFIX}.9"
    ports: !reset []
    restart: unless-stopped

  bareos-fd:
    networks:
      default:
        ipv4_address: "${NETWORK_PREFIX}.4"
    restart: unless-stopped
    volumes:
      - client_config:/etc/bareos
      - director_config:/etc/bareos-director:ro
      - director_data:/var/lib/bareos-director:ro # required for MyCatalog backup
      - storage_config:/etc/bareos-storage:ro
      - webui_config:/etc/bareos-webui:ro

  bareos-db:
    networks:
      default:
        ipv4_address: "${NETWORK_PREFIX}.7"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

  bareos-dir:
    environment:
      ADMIN_MAIL: ${ADMIN_MAIL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      SMTP_HOST: smtpd
    extra_hosts:
      - "sd1.${HOSTNAME}:${NETWORK_PREFIX}.3"
    networks:
      default:
        ipv4_address: "${NETWORK_PREFIX}.2"
    restart: unless-stopped
    volumes:
      - director_config:/etc/bareos
      - director_data:/var/lib/bareos # required for MyCatalog backup

  bareos-sd:
    networks:
      default:
        ipv4_address: "${NETWORK_PREFIX}.3"
    restart: unless-stopped
    volumes:
      - storage_config:/etc/bareos
      - storage_data:/var/lib/bareos/archive

  bareos-webui:
    restart: unless-stopped
    # Traefik labels are suggested as an example for people using Traefik,
    # remove them if you are using another reverse proxy.
    labels:
      traefik.enable: true
      traefik.http.routers.bareos-webui.entrypoints: websecure
      traefik.http.routers.bareos-webui.rule: "Host(`${HOSTNAME}`)"
      traefik.http.routers.bareos-webui.tls.certresolver: myresolver   
      traefik.http.services.bareos-webui.loadbalancer.server.port: 9100
    volumes:
      - webui_config:/etc/bareos-webui
      - webui_data:/usr/share/bareos-webui
    networks:
      web:
      default:
        ipv4_address: "${NETWORK_PREFIX}.5"
    ports: !reset []

  php-fpm:
    networks:
      default:
        ipv4_address: "${NETWORK_PREFIX}.6"
    volumes:
      - webui_config:/etc/bareos-webui
      - webui_data:/usr/share/bareos-webui

  smtpd:
    environment:
      RELAY_DOMAINS: ${SMTP_RELAY_DOMAINS}
      SMARTHOST_ADDRESS: ${SMTP_HOSTNAME}
      SMARTHOST_PORT: ${SMTP_PORT}
      SMARTHOST_USER_FILE: '/run/secrets/smtpd-user'
      SMARTHOST_PASSWORD_FILE: '/run/secrets/smtpd-password'
      SMARTHOST_ALIASES: ${SMTP_ALIASES}
    hostname: "smtpd.${HOSTNAME}"
    image: ixdotai/smtp
    networks:
      default:
        ipv4_address: "${NETWORK_PREFIX}.8"
    restart: unless-stopped
    secrets:
      - smtpd-user
      - smtpd-password
    volumes:
      - ../docker-volumes/smtpd/_docker_additional_macros:/etc/exim4/_docker_additional_macros
      - ../docker-volumes/smtpd/exim4.conf.template:/etc/exim4/exim4.conf.template

volumes:
  client_config:
  director_config:
  director_data:
  pg_data:
  storage_config:
  storage_data:
  webui_config:
  webui_data:
